### ISSUE TITLE
Parameter 1 Must be a Buffer

### ISSUE THREAD

**Issue by waldandrade** [PeculiarVentures/graphene-cli#4]
After i made all instalattions, i did executed slot open --slot 0 --pin 123456

and it returns: Parameter 1 Must be a Buffer 

Help me, please!

**Comment by microshine** [comment]
@waldandrade 
I published new version of `graphene-cli`, there was a problem with End of line

Could you call command from opened `graphene-cli`
```
> slot list
```

Is there any slots in list?

If there are any slot, then you need to set index of slot for `slot open` command

It works for me
![image](https://cloud.githubusercontent.com/assets/7333669/21470965/0fa0fd30-cab0-11e6-917c-6693c0cd0be2.png)
![image](https://cloud.githubusercontent.com/assets/7333669/21470967/36f2f654-cab0-11e6-89ca-9d65cb95596d.png)

**Comment by rmhrisk** [comment]
@waldandrade will close this but please re-open if it still does not work for you.
