### ISSUE TITLE
Doesn't work in Windows

### ISSUE THREAD

**Issue by LumaRay** [PeculiarVentures/graphene-cli#8]
> $ graphene
>\> module load -l /c/Windows/System32/rtPKCS11ECP.dll -n 123
> 
> Error Win32 error 126
>     at Error (native) PKCS11::Load:136
> 
> Help:
>   loads a specified PKCS#11 module
> 
>   --lib          -l     Path to library
>   --name         -n     Name of module
> 
>   Commands:
>     ?              Prints help information

**Comment by rmhrisk** [comment]
That error means either:

A) the path you specified to the library was incorrect
B) the path was correct but a dependency of the file you specified is missing.

**Comment by sfergu** [comment]
FYI for anyone else that may come along this trail of breadcrumbs, for me on windows no matter how i specified the full path the the dll it would not load. however, completely omitting the path and just specifying the name of the dll allowed it to load successfully. 

` graphene module load -n 123 -l "acpkcs211.dll"`
